# Generated by Django 5.0.4 on 2024-05-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_tool_delete_consumables_delete_parts_delete_renttool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
