# Generated by Django 5.0.6 on 2024-05-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0010_tool_oldprice_alter_tool_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='is_actia',
            field=models.BooleanField(default=1, verbose_name='Акция?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='is_new',
            field=models.BooleanField(default=1, verbose_name='Новинка?'),
            preserve_default=False,
        ),
    ]
