# Generated by Django 5.0.6 on 2024-05-16 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0011_tool_is_actia_tool_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=1, upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='', verbose_name='Маленькая картинка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop_app.category', verbose_name='Категория'),
        ),
    ]
